### ISSUE TITLE
Update to support Visual Studio 2017

### ISSUE THREAD

**Issue by Backhage** [ChrisMarinos/FSharpKoans#46]
This is more of a feature request than a bugreport. I tried cloning the repo and open the solution with Visual Studio Community Edition 2017. There are however several problems. I tried to fix them but got stuck after creating a new solution, re-creating the Projects and adding the source files and the Nunit nuget package. I now get several compiler errors that I don't know how to fix.

To reproduce: Open the solution in Visual Studio 2017.

**Comment by dsyme** [comment]
@ChrisMarinos If you like we could move this project over to http://github.com/fsprojects to help allow the community to maintain the koans collectively?  thanks!

**Comment by ChrisMarinos** [comment]
@dsyme I'm not opposed to the move if it helps, but I'm not sure why it makes a difference in terms of allowing the community to maintain the koans since we're both collaborators on this repo, and I've been more than happy to moderate and approve any pull requests as they come in. My preference would be to keep the location the same to maintain the repository history, links, etc. that point to this location. Let me know if I'm missing something, though!

**Comment by dsyme** [comment]
@ChrisMarinos My experience is that locating projects in organizations (rather than individual accounts) encourages co-ownership, and sometimes allows orthogonal issues like this to be addressed by different owners (one looks after content, another looks after quality etc.).   When using a personal repo, there seems to be a default expectation that the individual will address everything. That expectation can be changed, but somehow I rarely see multiple active owners for long-term projects in personal spaces. By placing it in an organization, co-ownership seems to end up the default. This repo is also one where people might be interested in co-owning, helping to shape its future, e.g. by extending the Koans to cover new constructs, presenting the koans in new ways, adding CI to the repo to make sure the Koans run across all platforms (including Fable), and so on. Sergey Tihon has been a great co-owner of many fsprojects projects in this way. Not all projects benefit however - it kind of depends.  

If you move a project, Github automatically forwards all URL accesses, so you get web link continuity and repo history.  You can also rename the project and forwarding works. One option might be to move it and rename it to "FSharpKoansByChris" or the like, to keep the personal recognition (which I know can be useful as a CV element too), with a note in the header

Anyway, think it over.  Seeing this issue pop up just made me wonder :)

**Comment by dsyme** [comment]
@Backhage Fixed by #49

**Comment by dsyme** [comment]
@ChrisMarinos OK, I went through all outstanding PRs and issues and closed them out to get the project into a clean state.

**Comment by dsyme** [comment]
@ChrisMarinos If I did anything wrong please let me know :)

**Comment by Backhage** [comment]
Thanks for the quick responses and actions. Great!

**Comment by ChrisMarinos** [comment]
Thanks for taking the time to update everything, @dsyme!
